### ISSUE TITLE
[Windows] Compilation errors

### ISSUE THREAD

**Issue by sfhacker** [babelouest/iddawc#3]
Environment: Windows 10 x64
Compiler:       GCC 11.2.0

I'm trying to build master branch (from source) and I get a bunch compilation issues:

In file included from C:/msys/1.0/src/iddawc/src/iddawc.c:29:
C:/src/iddawc/include/iddawc.h:268:3: error: unknown type name 'uint'
  268 |   uint          response_type;
      |   ^~~~
C:/src/iddawc/include/iddawc.h:291:3: error: unknown type name 'uint'
  291 |   uint          result;
      |   ^~~~
C:/src/iddawc/include/iddawc.h:302:3: error: unknown type name 'uint'
  302 |   uint          expires_in;
      |   ^~~~
C:/src/iddawc/include/iddawc.h:306:3: error: unknown type name 'uint'
  306 |   uint          auth_method;
      |   ^~~~

Any assistance would be grateful.

Cheers.

**Comment by sfhacker** [comment]
More issues:

C:/src/iddawc/src/iddawc.c:670:9: error: implicit declaration of function 'ulfius_send_http_request'; did you mean 'ulfius_init_request'? [-Werror=implicit-function-declaration]
  670 |     if (ulfius_send_http_request(&request, &response) == U_OK) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
      |         ulfius_init_request

It seems to be related to cURL, but we don't use it.

**Comment by sfhacker** [comment]
Thanks for your prompt response and fix! Appreciated.

Just come across some other issues:

C:/src/iddawc/tools/idwcc/idwcc.c:27:10: fatal error: netinet/in.h: No such file or directory
   27 | #include <netinet/in.h>
      |          ^~~~~~~~~~~~~~
	  
C:/src/iddawc/tools/idwcc/idwcc.c:60:3: error: unknown type name 'uint'
   60 |   uint                ciba_status;
      |   ^~~~

We should try, whenever possible, to write portable code!
We should also test as much as we can (on different platforms/architecture).

Thanks for your contribution here.

**Comment by babelouest** [comment]
> C:/src/iddawc/tools/idwcc/idwcc.c:27:10: fatal error: netinet/in.h: No such file or directory

`netinet/in.h` is a POSIX standard, sorry your platform doesn't support it. I won't remove `netinet/in.h` features from my code, but I'll happily review a pull request you could provide to help your needs.

> We should try, whenever possible, to write portable code!
> We should also test as much as we can (on different platforms/architecture).

We should consider that we can't magically support all platforms that exist, as we work on linux based systems, and we don't have the time/resource to test the code on all other architectures.

**Comment by babelouest** [comment]
The remaining `uint` have been replaced in https://github.com/babelouest/iddawc/commit/f529d1ca7bc17bd865a426bfb2cb491d9eddf015 , closing this issue now
