### ISSUE TITLE
Less restricted License plan

### ISSUE THREAD

**Issue by mohsenomidi** [babelouest/iddawc#5]
Is there any plan to publish the c/c++ backend part under any less restricted license like MIT to be able to use the library in private applications?

**Comment by babelouest** [comment]
Hello,

The [LGPL license](https://github.com/babelouest/iddawc/blob/master/LICENSE) used allows to link iddawc as a shared library a program with any kind of license, even private.

So I'm not willing to change the license, sorry.

**Comment by mohsenomidi** [comment]
This is not allowed to use the shared library in commercial and closed source apps, am I right?

**Comment by babelouest** [comment]
Yes it's allowed to do so, here is an answer for example: https://softwareengineering.stackexchange.com/questions/47323/can-i-use-an-lgpl-licenced-library-in-my-commercial-app

The [LGPL license](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License) is different from the [GPL license](https://en.wikipedia.org/wiki/GNU_General_Public_License) as it allows to use it in a closed source environment, see https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License#Differences_from_the_GPL

The main restrictions I see in your case when using a LGPL code are:
- Do not statically link a LGPL code in your private application, use a shared library instead
- If you make changes in a LGPL code, your changes to this code only -not the rest of your application- remains LGPL, so you must provide the new code to your users

**Comment by mohsenomidi** [comment]
Thanks 🙏🙏
