### ISSUE TITLE
Facebook example broken

### ISSUE THREAD

**Issue by tbsmark86** [babelouest/iddawc#7]
Facebook example is not working anymore - possible just to old. I had to add
`I_OPT_TOKEN_METHOD, I_TOKEN_AUTH_METHOD_SECRET_POST,`

Not necessary but more useful response with slightly changed userinfo:
`#define USERINFO_ENDPOINT "https://graph.facebook.com/v5.0/me?fields=id,name,email"`

Also it seems like facebook is returning errors slightly different (not sure if if violates the rfc) making it more difficult to debug this - requiring a complete log of all http response and manual parsing.
The error returned looks like this:
`"{"error": {"message": "Error validating client secret.", "type": "OAuthException", "code": 1, "fbtrace_id": "..."}}"`
Instead of a simple string for the error field.
Would be nice if you could change so that these errors also appear in I_OPT_ERROR/I_OPT_ERROR_DESCRIPTION.

Furthermore/more general it feels like the lib is a black hole for unhandled server response. I suggest to put at least a minimal
status like "unknown error response" into I_OPT_ERROR. Or, if possible, the http status code.
Maybe even copy the full response body to I_OPT_ERROR_DESCRIPTION in that case.

Last but not least: The fact that I_OPT_ERROR can be used to query the remote errors seems to be missing from the API documentation.

**Comment by babelouest** [comment]
Hello,

Thanks for reporting the issue, I'll fix the facebook example with your feedback. I'll update all the examples with the same changes because I guess they have the same problem.

The error message in the token endpoint doesn't seem to break the RFC because it only states about the http status, the response body isn't mentioned if I recall properly. The idea to report the error messages in the `I_OPT_ERROR` and/or `I_OPT_ERROR_DESCRIPTION` seems to be a good idea, I'll add this feature soon when I'll have a few minutes.

I'll also improve the documentation about the remote error.

Thanks!

**Comment by babelouest** [comment]
Hello @tbsmark86 ,

The error message and description are already stored in `I_OPT_ERROR` and/or `I_OPT_ERROR_DESCRIPTION` in a token request, I just didn't remember it...

I've updated the [examples](https://github.com/babelouest/iddawc/blob/master/examples/facebook_example.c#L46) to add the `I_OPT_TOKEN_METHOD` in each of them.

I've also updated the documentation on the `i_parse_redirect_to`, `i_run_token_request` functions and added a paragraph on how to use the [Export HTTP requests and responses](https://github.com/babelouest/iddawc/blob/master/API.md#export-http-requests-and-responses).

Let me know if some documentation should be more clear.

**Comment by tbsmark86** [comment]
About the document: The most important point is that its now mentioned that those fields are available.
So I think that's OK.

> The error message and description are already stored 

Yes; but you did forget my point about facebook using a different format. Or more general every format that is not matching what _i_parse_error_response is expecting will leave both fields empty.

I'am using the saved response doing my own error parsing to get around this.

Some dry-code idea:
https://github.com/babelouest/iddawc/blob/db69b4da5547b24470d5c70b7181e160539ba57f/src/iddawc.c#L820
```
    if (json_string_length(json_object_get(j_response, "error")) && i_set_str_parameter(i_session, I_OPT_ERROR, json_string_value(json_object_get(j_response, "error"))) != I_OK) {
      y_log_message(Y_LOG_LEVEL_ERROR, "_i_parse_error_response - Error setting error");
      ret = I_ERROR;
    } else {
       json_t *err_obj = json_object_get(j_response, "error")
      if(json_is_object(err_obj) && json_string_length(json_object_get(err_obj, "message")) && i_set_str_parameter(i_session, I_OPT_ERROR, json_string_value(json_object_get(err_obj, "message"))) != I_OK) {
          y_log_message(Y_LOG_LEVEL_ERROR, "_i_parse_error_response - Error setting error");
          ret = I_ERROR;
       } else {
         i_set_str_parameter(i_session, I_OPT_ERROR, "error response in unknown format");
      }
```

One could also argue that here:
https://github.com/babelouest/iddawc/blob/db69b4da5547b24470d5c70b7181e160539ba57f/src/iddawc.c#L4425
and
https://github.com/babelouest/iddawc/blob/db69b4da5547b24470d5c70b7181e160539ba57f/src/iddawc.c#L3431
should return I_SERVER_ERROR?

Oh and 
https://github.com/babelouest/iddawc/blob/db69b4da5547b24470d5c70b7181e160539ba57f/src/iddawc.c#L3426
should write "(2)" as a message?

**Comment by babelouest** [comment]
Thanks @tbsmark86 ,

I've updated the code to return `I_ERROR_SERVER` when the response status is 500-599, and `I_ERROR` otherwise.

I also updated the log messages to be more descriptive than (1) or (2).
