### ISSUE TITLE
Regression introduced in iddawc 1.1.9 _i_send_http_request

### ISSUE THREAD

**Issue by zagar** [babelouest/iddawc#8]
In iddawc 1.1.9, _i_send_http_request was changed to verify the value in the Content-Length header against the length of the content received. In the absence of this header, this error is reported "_i_send_http_request - Error no Content-Length header" and the request fails.

The Content-Length header is optional and often omitted when content is sent using chunking. I ran into a server that doesn't include this header in its response that worked under 1.1.8 but failed with this error under 1.1.9 as a result.

In testing, I confirmed that commenting out 

      y_log_message(Y_LOG_LEVEL_ERROR, "_i_send_http_request - Error no Content-Length header");
      ret = I_ERROR;

restores the 1.1.8 behavior.

Would you please consider either removing the final else containing these lines that enforce this requirement or else consider adding an option to disable this from being mandatory?

**Comment by babelouest** [comment]
Hello @zagar ,

Thanks for the big report. Indeed the check for the `content-length` header value seems overkill. Its goal is to prevent malicious website to overflow the oauth2 client. But this header isn't mandatory so it may lead to errors like yours.

In that case, setting `I_OPT_RESPONSE_MAX_BODY_SIZE` should be enough.

I'll remove the `content-length` check after verifying it doesn't break anything else.

**Comment by chriszagaremcc** [comment]
Hello @babelouest ,

Thank you for looking into this. I'll be glad to test it out once a change is applied. Do you have any rough projection of when you might be releasing 1.1.10?

**Comment by babelouest** [comment]
Thanks, the code has been fixed in https://github.com/babelouest/iddawc/commit/68f3ebefe404a722ffb4b7ec2b79b7390bede717 , can you test it again and check if your problem is fixed?

Concerning the next release, there are no big changes since 1.1.9 yet (except for your bugfix), so I don't have a release date yet.

**Comment by chriszagaremcc** [comment]
That version fixes the problem I was encountering. Thank you!
